<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Angel\QoH\Block\Tickets\Index $block */
?>
<?php $_tickets = $block->getOrderedTickets(); ?>
<?php if ($_tickets && count($_tickets)): ?>
    <h1><?= /* @escapeNotVerified */ __('Your new tickets') ?></h1>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-tickets-table">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Tickets') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col name"><?= /* @escapeNotVerified */ __('Name') ?></th>
                <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Start') ?></th>
                <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('End') ?></th>
                <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Board Number') ?></th>
                <th scope="col" class="col total"><?= /* @escapeNotVerified */ __('Price') ?></th>
                <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Purchased At') ?></th>
                <th scope="col" class="col status"><?= /* @escapeNotVerified */ __('Status') ?></th>
                <th scope="col" class="col actions"><?= /* @escapeNotVerified */ __('Action') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php /** @var \Angel\QoH\Model\Data\Ticket $_ticket */ ?>
            <?php foreach ($_tickets as $_ticket): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Name')) ?>" class="col id"><a href="<?= $block->getUrl('catalog/product/view', ['id' => $_ticket->getProductId()]) ?>" ><?= /* @escapeNotVerified */ $_ticket->getProductName() ?></a></td>
                    <td data-th="<?= $block->escapeHtml(__('Start Number')) ?>" class="col id"><?= /* @escapeNotVerified */ $_ticket->getStart() ?></td>
                    <td data-th="<?= $block->escapeHtml(__('End Number')) ?>" class="col id"><?= /* @escapeNotVerified */ $_ticket->getEnd() ?></td>
                    <td data-th="<?= $block->escapeHtml(__('End Number')) ?>" class="col id"><?= /* @escapeNotVerified */ $_ticket->getCardNumber() ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Price')) ?>" class="col total"><?= /* @escapeNotVerified */ $block->formatPrice($_ticket->getPrice()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Purchased At')) ?>" class="col date"><?= /* @escapeNotVerified */ $block->formatDate($_ticket->getCreatedAt(), 2 , true) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= /* @escapeNotVerified */ $block->getStatusLabel($_ticket) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <?php if (0&&$_ticket->getStatus() == \Angel\QoH\Model\Ticket\Status::STATUS_LOSE || $_ticket->getStatus() == \Angel\QoH\Model\Ticket\Status::STATUS_CANCELED): ?>
                            <a href="<?= /* @escapeNotVerified */ $block->getTrashUrl($_ticket) ?>" class="action view">
                                <span><?= /* @escapeNotVerified */ __('Move To Trash') ?></span>
                            </a>
                        <?php endif; ?>
                        <button class="print-receipt" type="button" ticket_id="<?= $_ticket->getId() ?>"><?= __('Print Receipt') ?></button>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
    <script type="text/x-magento-init">
        {
            ".print-receipt": {
                "Angel_QoH/js/print-receipt": {}
            }
        }
    </script>
    <div id="printReceipt" data-bind="scope:'printReceipt'">
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#printReceipt": {
                    "Magento_Ui/js/core/app": {
                        "components" : {
                            "printReceipt" : {
                                "component": "Angel_QoH/js/view/print-receipt"
                            }
                        }
                    }
                }
            }
        </script>
    </div>
<?php endif ?>
