<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Angel\QoH\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
if($customerSession->isLoggedIn()) {
    $buttonTitle = __('Purchase Tickets');
} else {
    $buttonTitle = __('Login To Purchase');
}
?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <div id="customerCredit" data-bind="scope:'customerCredit'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <div id="qoh" data-bind="scope:'qoh'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div id="queenOfHeartsCardSelectBox" data-bind="scope:'queenOfHeartsCardSelectBox'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <input type="hidden" name="sku" value="<?= $_product->getSku() ?>" />
            <div class="actions">
                <button type="submit"
                        title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                        class="action primary tocart disabled"
                        id="product-addtocart-button">
                    <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<div id="qohTicket" data-bind="scope:'qohTicket'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<div id="qohPrizes" data-bind="scope:'qohPrizes'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "#queenOfHeartsCardSelectBox": {
            "Magento_Ui/js/core/app": {
                "components" : {
                    "queenOfHeartsCardSelectBox" : {
                        "component": "Angel_QoH/js/view/card-select-box"
                    }
                }
            }
        },
        "#qohTicket": {
            "Magento_Ui/js/core/app": {
                "components" : {
                    "qohTicket" : {
                        "component": "Angel_QoH/js/view/tickets"
                    }
                }
            }
        },
        "#customerCredit": {
            "Magento_Ui/js/core/app": {
                "components" : {
                    "customerCredit" : {
                        "component": "Magestore_Customercredit/js/view/current-credit-balance"
                    }
                }
            }
        },
        "#qoh": {
            "Magento_Ui/js/core/app": {
                "components" : {
                    "qoh" : {
                        "component": "Angel_QoH/js/view/queen-of-hearts"
                    }
                }
            }
        }
    }
</script>