<div id="qohTicket" data-bind="scope:'qohTicket'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#qohTicket": {
                "Magento_Ui/js/core/app": {
                    "components" : {
                        "qohTicket" : {
                            "component": "Angel_QoH/js/view/tickets"
                        }
                    }
                }
            }
        }
    </script>
</div>